version: '2'
services: 
    db_lara_skeleton: 
        container_name: dbLaraSkeleton
        image: mysql:5.6
        volumes: 
            - dbdata:/var/lib/mysql
        environment: 
            - "MYSQL_DATABASE=lara_skeleton"
            - "MYSQL_USER=laraenv"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=1234567"
            - "MYSQL_PORT=3306"
        ports: 
            - 3306:3306    
        networks: 
            laravelSkeleton: 
                ipv4_address: 172.20.0.10

    app_lara_skeleton: 
        container_name: appLaraSkeleton
        build: 
            context: . 
            dockerfile: app.Dockerfile
        ports: 
            - 8001:8000    
        working_dir: /var/www
        volumes: 
            - /var/www/storage
            - ./:/var/www
        env_file: '.env'
        environment: 
            - "DB_HOST=database"
            - "DB_PORT=3306"
        links: 
            - db_lara_skeleton
        depends_on: 
            - db_lara_skeleton
        networks: 
            laravelSkeleton: 
                ipv4_address: 172.20.0.11
    
    web: 
        container_name: nginx
        build: 
            context: . 
            dockerfile: web.Dockerfile
        ports: 
            - 8080:80
        links: 
            - app_lara_skeleton
        networks: 
            - laravelSkeleton
        volumes: 
            - ./:/var/www 
            - ./access.log:/var/log/nginx/access.log
            - ./error.log:/var/log/nginx/error.log 
        networks: 
            laravelSkeleton:
                ipv4_address: 172.20.0.12

networks: 
    laravelSkeleton:   
        driver: bridge
        ipam: 
            config: 
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1     
volumes: 
    dbdata: